SELECT CONCAT("<a href='https://www.strava.com/segments/",segment_id,"/' rel='noopener noreferrer' target='_blank'>",segment_id,'</a>') as segment, ranking FROM (
select segment_id, '  kom' as ranking,  if(entries[0].athlete_id=ATHLETEID and entries[0].rank=1, 1, if(entries[1].athlete_id=ATHLETEID and entries[1].rank=1, 1, if(entries[2].athlete_id=ATHLETEID and entries[2].rank=1, 1, if(entries[3].athlete_id=ATHLETEID and entries[3].rank=1, 1, if(entries[4].athlete_id=ATHLETEID and entries[4].rank=1, 1, if(entries[5].athlete_id=ATHLETEID and entries[5].rank=1, 1, if(entries[6].athlete_id=ATHLETEID and entries[6].rank=1, 1, if(entries[7].athlete_id=ATHLETEID and entries[7].rank=1, 1, if(entries[8].athlete_id=ATHLETEID and entries[8].rank=1, 1, if(entries[9].athlete_id=ATHLETEID and entries[9].rank=1, 1, 0)))))))))) as segrank from leaderboardforsegment WHERE segrank > 0
UNION
select segment_id, ' 2nd' as ranking, if(entries[1].athlete_id=ATHLETEID and entries[1].rank=2, 1, if(entries[2].athlete_id=ATHLETEID and entries[2].rank=2, 1, if(entries[3].athlete_id=ATHLETEID and entries[3].rank=2, 1, if(entries[4].athlete_id=ATHLETEID and entries[4].rank=2, 1, if(entries[5].athlete_id=ATHLETEID and entries[5].rank=2, 1, if(entries[6].athlete_id=ATHLETEID and entries[6].rank=2, 1, if(entries[7].athlete_id=ATHLETEID and entries[7].rank=2, 1, if(entries[8].athlete_id=ATHLETEID and entries[8].rank=2, 1, if(entries[9].athlete_id=ATHLETEID and entries[9].rank=2, 1, 0))))))))) as segrank from leaderboardforsegment WHERE segrank > 0
UNION
select segment_id, ' 3rd' as ranking, if(entries[2].athlete_id=ATHLETEID and entries[2].rank=3, 1, if(entries[3].athlete_id=ATHLETEID and entries[3].rank=3, 1, if(entries[4].athlete_id=ATHLETEID and entries[4].rank=3, 1, if(entries[5].athlete_id=ATHLETEID and entries[5].rank=3, 1, if(entries[6].athlete_id=ATHLETEID and entries[6].rank=3, 1, if(entries[7].athlete_id=ATHLETEID and entries[7].rank=3, 1, if(entries[8].athlete_id=ATHLETEID and entries[8].rank=3, 1, if(entries[9].athlete_id=ATHLETEID and entries[9].rank=3, 1, 0)))))))) as segrank from leaderboardforsegment WHERE segrank > 0
UNION
select segment_id, ' 4th' as ranking, if(entries[3].athlete_id=ATHLETEID and entries[3].rank=4, 1, if(entries[4].athlete_id=ATHLETEID and entries[4].rank=4, 1, if(entries[5].athlete_id=ATHLETEID and entries[5].rank=4, 1, if(entries[6].athlete_id=ATHLETEID and entries[6].rank=4, 1, if(entries[7].athlete_id=ATHLETEID and entries[7].rank=4, 1, if(entries[8].athlete_id=ATHLETEID and entries[8].rank=4, 1, if(entries[9].athlete_id=ATHLETEID and entries[9].rank=4, 1, 0))))))) as segrank from leaderboardforsegment WHERE segrank > 0
UNION
select segment_id, ' 5th' as ranking, if(entries[4].athlete_id=ATHLETEID and entries[4].rank=5, 1, if(entries[5].athlete_id=ATHLETEID and entries[5].rank=5, 1, if(entries[6].athlete_id=ATHLETEID and entries[6].rank=5, 1, if(entries[7].athlete_id=ATHLETEID and entries[7].rank=5, 1, if(entries[8].athlete_id=ATHLETEID and entries[8].rank=5, 1, if(entries[9].athlete_id=ATHLETEID and entries[9].rank=5, 1, 0)))))) as segrank from leaderboardforsegment WHERE segrank > 0
UNION
select segment_id, ' 6th' as ranking, if(entries[5].athlete_id=ATHLETEID and entries[5].rank=6, 1, if(entries[6].athlete_id=ATHLETEID and entries[6].rank=6, 1, if(entries[7].athlete_id=ATHLETEID and entries[7].rank=6, 1, if(entries[8].athlete_id=ATHLETEID and entries[8].rank=6, 1, if(entries[9].athlete_id=ATHLETEID and entries[9].rank=6, 1, 0))))) as segrank from leaderboardforsegment WHERE segrank > 0
UNION
select segment_id, ' 7th' as ranking, if(entries[6].athlete_id=ATHLETEID and entries[6].rank=7, 1, if(entries[7].athlete_id=ATHLETEID and entries[7].rank=7, 1, if(entries[8].athlete_id=ATHLETEID and entries[8].rank=7, 1, if(entries[9].athlete_id=ATHLETEID and entries[9].rank=7, 1, 0)))) as segrank from leaderboardforsegment WHERE segrank > 0
UNION
select segment_id, ' 8th' as ranking, if(entries[7].athlete_id=ATHLETEID and entries[7].rank=8, 1, if(entries[8].athlete_id=ATHLETEID and entries[8].rank=8, 1, if(entries[9].athlete_id=ATHLETEID and entries[9].rank=8, 1, 0))) as segrank from leaderboardforsegment WHERE segrank > 0
UNION
select segment_id, ' 9th' as ranking, if(entries[8].athlete_id=ATHLETEID and entries[8].rank=9, 1, if(entries[9].athlete_id=ATHLETEID and entries[9].rank=9, 1, 0)) as segrank from leaderboardforsegment WHERE segrank > 0
UNION
select segment_id, '10th' as ranking, if(entries[9].athlete_id=ATHLETEID and entries[9].rank=10, 1, 0) as segrank from leaderboardforsegment WHERE segrank > 0
) AS T2
WHERE segrank > 0
ORDER BY ranking;
