insert overwrite table swaggercupcount select b.segment_id, regexp_replace(a.segment_name, '[^\\x20-\\x7A]+', ''), '  kom' as ranking, if(b.entries[0].athlete_id=ATHLETEID and b.entries[0].rank=1, 1, if(b.entries[1].athlete_id=ATHLETEID and b.entries[1].rank=1, 1, if(b.entries[2].athlete_id=ATHLETEID and b.entries[2].rank=1, 1, if(b.entries[3].athlete_id=ATHLETEID and b.entries[3].rank=1, 1, if(b.entries[4].athlete_id=ATHLETEID and b.entries[4].rank=1, 1, if(b.entries[5].athlete_id=ATHLETEID and b.entries[5].rank=1, 1, if(b.entries[6].athlete_id=ATHLETEID and b.entries[6].rank=1, 1, if(b.entries[7].athlete_id=ATHLETEID and b.entries[7].rank=1, 1, if(b.entries[8].athlete_id=ATHLETEID and b.entries[8].rank=1, 1, if(b.entries[9].athlete_id=ATHLETEID and b.entries[9].rank=1, 1, 0)))))))))) as segrank from leaderboardforsegment b JOIN besteffortforsegments a on b.segment_id = a.segment_id;

insert into table swaggercupcount select b.segment_id, regexp_replace(a.segment_name, '[^\\x20-\\x7A]+', ''), ' 2nd' as ranking, if(b.entries[1].athlete_id=ATHLETEID and b.entries[1].rank=2, 1, if(b.entries[2].athlete_id=ATHLETEID and b.entries[2].rank=2, 1, if(b.entries[3].athlete_id=ATHLETEID and b.entries[3].rank=2, 1, if(b.entries[4].athlete_id=ATHLETEID and b.entries[4].rank=2, 1, if(b.entries[5].athlete_id=ATHLETEID and b.entries[5].rank=2, 1, if(b.entries[6].athlete_id=ATHLETEID and b.entries[6].rank=2, 1, if(b.entries[7].athlete_id=ATHLETEID and b.entries[7].rank=2, 1, if(b.entries[8].athlete_id=ATHLETEID and b.entries[8].rank=2, 1, if(b.entries[9].athlete_id=ATHLETEID and b.entries[9].rank=2, 1, 0))))))))) as segrank from leaderboardforsegment b JOIN besteffortforsegments a on b.segment_id = a.segment_id;

insert into table swaggercupcount select b.segment_id, regexp_replace(a.segment_name, '[^\\x20-\\x7A]+', ''), ' 3rd' as ranking, if(b.entries[2].athlete_id=ATHLETEID and b.entries[2].rank=3, 1, if(b.entries[3].athlete_id=ATHLETEID and b.entries[3].rank=3, 1, if(b.entries[4].athlete_id=ATHLETEID and b.entries[4].rank=3, 1, if(b.entries[5].athlete_id=ATHLETEID and b.entries[5].rank=3, 1, if(b.entries[6].athlete_id=ATHLETEID and b.entries[6].rank=3, 1, if(b.entries[7].athlete_id=ATHLETEID and b.entries[7].rank=3, 1, if(b.entries[8].athlete_id=ATHLETEID and b.entries[8].rank=3, 1, if(b.entries[9].athlete_id=ATHLETEID and b.entries[9].rank=3, 1, 0)))))))) as segrank from leaderboardforsegment b JOIN besteffortforsegments a on b.segment_id = a.segment_id;

insert into table swaggercupcount select b.segment_id, regexp_replace(a.segment_name, '[^\\x20-\\x7A]+', ''), ' 4th' as ranking, if(b.entries[3].athlete_id=ATHLETEID and b.entries[3].rank=4, 1, if(b.entries[4].athlete_id=ATHLETEID and b.entries[4].rank=4, 1, if(b.entries[5].athlete_id=ATHLETEID and b.entries[5].rank=4, 1, if(b.entries[6].athlete_id=ATHLETEID and b.entries[6].rank=4, 1, if(b.entries[7].athlete_id=ATHLETEID and b.entries[7].rank=4, 1, if(b.entries[8].athlete_id=ATHLETEID and b.entries[8].rank=4, 1, if(b.entries[9].athlete_id=ATHLETEID and b.entries[9].rank=4, 1, 0))))))) as segrank from leaderboardforsegment b JOIN besteffortforsegments a on b.segment_id = a.segment_id;

insert into table swaggercupcount select b.segment_id, regexp_replace(a.segment_name, '[^\\x20-\\x7A]+', ''), ' 5th' as ranking, if(b.entries[4].athlete_id=ATHLETEID and b.entries[4].rank=5, 1, if(b.entries[5].athlete_id=ATHLETEID and b.entries[5].rank=5, 1, if(b.entries[6].athlete_id=ATHLETEID and b.entries[6].rank=5, 1, if(b.entries[7].athlete_id=ATHLETEID and b.entries[7].rank=5, 1, if(b.entries[8].athlete_id=ATHLETEID and b.entries[8].rank=5, 1, if(b.entries[9].athlete_id=ATHLETEID and b.entries[9].rank=5, 1, 0)))))) as segrank from leaderboardforsegment b JOIN besteffortforsegments a on b.segment_id = a.segment_id;

insert into table swaggercupcount select b.segment_id, regexp_replace(a.segment_name, '[^\\x20-\\x7A]+', ''), ' 6th' as ranking, if(b.entries[5].athlete_id=ATHLETEID and b.entries[5].rank=6, 1, if(b.entries[6].athlete_id=ATHLETEID and b.entries[6].rank=6, 1, if(b.entries[7].athlete_id=ATHLETEID and b.entries[7].rank=6, 1, if(b.entries[8].athlete_id=ATHLETEID and b.entries[8].rank=6, 1, if(b.entries[9].athlete_id=ATHLETEID and b.entries[9].rank=6, 1, 0))))) as segrank from leaderboardforsegment b JOIN besteffortforsegments a on b.segment_id = a.segment_id;

insert into table swaggercupcount select b.segment_id, regexp_replace(a.segment_name, '[^\\x20-\\x7A]+', ''), ' 7th' as ranking, if(b.entries[6].athlete_id=ATHLETEID and b.entries[6].rank=7, 1, if(b.entries[7].athlete_id=ATHLETEID and b.entries[7].rank=7, 1, if(b.entries[8].athlete_id=ATHLETEID and b.entries[8].rank=7, 1, if(b.entries[9].athlete_id=ATHLETEID and b.entries[9].rank=7, 1, 0)))) as segrank from leaderboardforsegment b JOIN besteffortforsegments a on b.segment_id = a.segment_id;

insert into table swaggercupcount select b.segment_id, regexp_replace(a.segment_name, '[^\\x20-\\x7A]+', ''), ' 8th' as ranking, if(b.entries[7].athlete_id=ATHLETEID and b.entries[7].rank=8, 1, if(b.entries[8].athlete_id=ATHLETEID and b.entries[8].rank=8, 1, if(b.entries[9].athlete_id=ATHLETEID and b.entries[9].rank=8, 1, 0))) as segrank from leaderboardforsegment b JOIN besteffortforsegments a on b.segment_id = a.segment_id;

insert into table swaggercupcount select b.segment_id, regexp_replace(a.segment_name, '[^\\x20-\\x7A]+', ''), ' 9th' as ranking, if(b.entries[8].athlete_id=ATHLETEID and b.entries[8].rank=9, 1, if(b.entries[9].athlete_id=ATHLETEID and b.entries[9].rank=9, 1, 0)) as segrank from leaderboardforsegment b JOIN besteffortforsegments a on b.segment_id = a.segment_id;

insert into table swaggercupcount select b.segment_id, regexp_replace(a.segment_name, '[^\\x20-\\x7A]+', ''), '10th' as ranking, if(b.entries[9].athlete_id=ATHLETEID and b.entries[9].rank=10, 1, 0) as segrank from leaderboardforsegment b JOIN besteffortforsegments a on b.segment_id = a.segment_id;

SELECT CONCAT("<a href='https://www.strava.com/segments/",segment_id,"/' rel='noopener noreferrer' target='_blank'>",segment_name,'</a>') as segment, ranking
FROM swaggercupcount
WHERE segrank > 0
ORDER BY ranking;
